### EDA of surface weather data

In [46]:
# Packages
import numpy as np
import pandas as pd
from astropy.time import Time
from astropy.coordinates import get_sun, AltAz, EarthLocation
import astropy.units as u
from datetime import datetime

In [2]:
# Load dataset
df_b = pd.read_excel('../data/bronx_mesonet_weather_data.xlsx')
df_m = pd.read_excel('../data/manhattan_mesonet_weather_data.xlsx')

In [3]:
# Statistical description of float columns
df_b.describe()

,Air Temp at Surface [degC],Relative Humidity [percent],Avg Wind Speed [m/s],Wind Direction [degrees],Solar Flux [W/m^2]
count,169.000000,169.000000,169.000000,169.000000,169.000000
mean,24.789941,54.445562,2.348521,128.479290,387.869822
std,2.590496,11.844493,1.023364,92.281601,262.097914
min,19.300000,39.600000,0.200000,1.000000,12.000000
25%,23.900000,47.400000,1.600000,52.000000,156.000000
50%,25.500000,49.800000,2.200000,128.000000,330.000000
75%,26.700000,56.500000,3.100000,168.000000,618.000000
max,28.400000,88.200000,4.800000,359.000000,960.000000

In [4]:
# Statistical description of float columns
df_m.describe()

,Air Temp at Surface [degC],Relative Humidity [percent],Avg Wind Speed [m/s],Wind Direction [degrees],Solar Flux [W/m^2]
count,169.000000,169.000000,169.000000,169.000000,169.000000
mean,25.198225,49.401775,1.931953,134.863905,380.000000
std,1.696547,6.103468,0.799358,86.477491,262.528479
min,21.300000,39.200000,0.600000,2.000000,10.000000
25%,24.400000,45.900000,1.300000,61.000000,140.000000
50%,25.300000,48.000000,1.900000,144.000000,321.000000
75%,26.500000,51.100000,2.400000,171.000000,620.000000
max,27.900000,66.500000,4.100000,355.000000,840.000000

In [5]:
# Counting NaNs
print(df_b.isna().sum())
print("================================")
print(df_m.isna().sum())

Date / Time                    0
Air Temp at Surface [degC]     0
Relative Humidity [percent]    0
Avg Wind Speed [m/s]           0
Wind Direction [degrees]       0
Solar Flux [W/m^2]             0
dtype: int64
================================
Date / Time                    0
Air Temp at Surface [degC]     0
Relative Humidity [percent]    0
Avg Wind Speed [m/s]           0
Wind Direction [degrees]       0
Solar Flux [W/m^2]             0
dtype: int64

In [25]:
# Convert Date and Time column in datetime objects
df_b[df_b.columns[0]] = pd.to_datetime(df_b[df_b.columns[0]])

/home/scollazo/anaconda3/envs/env-ml/lib/python3.10/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

In [29]:
# Convert Date and Time column in datetime objects
df_m[df_m.columns[0]] = pd.to_datetime(df_m[df_m.columns[0]])

/home/scollazo/anaconda3/envs/env-ml/lib/python3.10/site-packages/dateutil/parser/_parser.py:1207: UnknownTimezoneWarning: tzname EDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

In [61]:
# UTC difference
utcoffset = -4*u.hour                                 # EDT (Eastern Daylight Time)

# Set time
t = Time(df_m[df_m.columns[0]]) - utcoffset

In [62]:
sun = get_sun(t)

In [63]:
sun

<SkyCoord (GCRS: obstime=['2021-07-24T10:00:00.000000000' '2021-07-24T10:05:00.000000000'
 '2021-07-24T10:10:00.000000000' '2021-07-24T10:15:00.000000000'
 '2021-07-24T10:20:00.000000000' '2021-07-24T10:25:00.000000000'
 '2021-07-24T10:30:00.000000000' '2021-07-24T10:35:00.000000000'
 '2021-07-24T10:40:00.000000000' '2021-07-24T10:45:00.000000000'
 '2021-07-24T10:50:00.000000000' '2021-07-24T10:55:00.000000000'
 '2021-07-24T11:00:00.000000000' '2021-07-24T11:05:00.000000000'
 '2021-07-24T11:10:00.000000000' '2021-07-24T11:15:00.000000000'
 '2021-07-24T11:20:00.000000000' '2021-07-24T11:25:00.000000000'
 '2021-07-24T11:30:00.000000000' '2021-07-24T11:35:00.000000000'
 '2021-07-24T11:40:00.000000000' '2021-07-24T11:45:00.000000000'
 '2021-07-24T11:50:00.000000000' '2021-07-24T11:55:00.000000000'
 '2021-07-24T12:00:00.000000000' '2021-07-24T12:05:00.000000000'
 '2021-07-24T12:10:00.000000000' '2021-07-24T12:15:00.000000000'
 '2021-07-24T12:20:00.000000000' '2021-07-24T12:25:00.000000000'
 '2021-07-24T12:30:00.000000000' '2021-07-24T12:35:00.000000000'
 '2021-07-24T12:40:00.000000000' '2021-07-24T12:45:00.000000000'
 '2021-07-24T12:50:00.000000000' '2021-07-24T12:55:00.000000000'
 '2021-07-24T13:00:00.000000000' '2021-07-24T13:05:00.000000000'
 '2021-07-24T13:10:00.000000000' '2021-07-24T13:15:00.000000000'
 '2021-07-24T13:20:00.000000000' '2021-07-24T13:25:00.000000000'
 '2021-07-24T13:30:00.000000000' '2021-07-24T13:35:00.000000000'
 '2021-07-24T13:40:00.000000000' '2021-07-24T13:45:00.000000000'
 '2021-07-24T13:50:00.000000000' '2021-07-24T13:55:00.000000000'
 '2021-07-24T14:00:00.000000000' '2021-07-24T14:05:00.000000000'
 '2021-07-24T14:10:00.000000000' '2021-07-24T14:15:00.000000000'
 '2021-07-24T14:20:00.000000000' '2021-07-24T14:25:00.000000000'
 '2021-07-24T14:30:00.000000000' '2021-07-24T14:35:00.000000000'
 '2021-07-24T14:40:00.000000000' '2021-07-24T14:45:00.000000000'
 '2021-07-24T14:50:00.000000000' '2021-07-24T14:55:00.000000000'
 '2021-07-24T15:00:00.000000000' '2021-07-24T15:05:00.000000000'
 '2021-07-24T15:10:00.000000000' '2021-07-24T15:15:00.000000000'
 '2021-07-24T15:20:00.000000000' '2021-07-24T15:25:00.000000000'
 '2021-07-24T15:30:00.000000000' '2021-07-24T15:35:00.000000000'
 '2021-07-24T15:40:00.000000000' '2021-07-24T15:45:00.000000000'
 '2021-07-24T15:50:00.000000000' '2021-07-24T15:55:00.000000000'
 '2021-07-24T16:00:00.000000000' '2021-07-24T16:05:00.000000000'
 '2021-07-24T16:10:00.000000000' '2021-07-24T16:15:00.000000000'
 '2021-07-24T16:20:00.000000000' '2021-07-24T16:25:00.000000000'
 '2021-07-24T16:30:00.000000000' '2021-07-24T16:35:00.000000000'
 '2021-07-24T16:40:00.000000000' '2021-07-24T16:45:00.000000000'
 '2021-07-24T16:50:00.000000000' '2021-07-24T16:55:00.000000000'
 '2021-07-24T17:00:00.000000000' '2021-07-24T17:05:00.000000000'
 '2021-07-24T17:10:00.000000000' '2021-07-24T17:15:00.000000000'
 '2021-07-24T17:20:00.000000000' '2021-07-24T17:25:00.000000000'
 '2021-07-24T17:30:00.000000000' '2021-07-24T17:35:00.000000000'
 '2021-07-24T17:40:00.000000000' '2021-07-24T17:45:00.000000000'
 '2021-07-24T17:50:00.000000000' '2021-07-24T17:55:00.000000000'
 '2021-07-24T18:00:00.000000000' '2021-07-24T18:05:00.000000000'
 '2021-07-24T18:10:00.000000000' '2021-07-24T18:15:00.000000000'
 '2021-07-24T18:20:00.000000000' '2021-07-24T18:25:00.000000000'
 '2021-07-24T18:30:00.000000000' '2021-07-24T18:35:00.000000000'
 '2021-07-24T18:40:00.000000000' '2021-07-24T18:45:00.000000000'
 '2021-07-24T18:50:00.000000000' '2021-07-24T18:55:00.000000000'
 '2021-07-24T19:00:00.000000000' '2021-07-24T19:05:00.000000000'
 '2021-07-24T19:10:00.000000000' '2021-07-24T19:15:00.000000000'
 '2021-07-24T19:20:00.000000000' '2021-07-24T19:25:00.000000000'
 '2021-07-24T19:30:00.000000000' '2021-07-24T19:35:00.000000000'
 '2021-07-24T19:40:00.000000000' '2021-07-24T19:45:00.000000000'
 '2021-07-24T19:50:00.000000000' '2021-07-24T19:55:00.000000000'
 '2021-07-24T20:00:00.000000000' '2021-07-24T20:05:00.000000000'
 '2021-07-24T20:10:00.000000000' '2021-07-24T20:15:00.000000000'
 '2021-07-24T20:20:00.000000000' '2021-07-24T20:25:00.000000000'
 '2021-07-24T20:30:00.000000000' '2021-07-24T20:35:00.000000000'
 '2021-07-24T20:40:00.000000000' '2021-07-24T20:45:00.000000000'
 '2021-07-24T20:50:00.000000000' '2021-07-24T20:55:00.000000000'
 '2021-07-24T21:00:00.000000000' '2021-07-24T21:05:00.000000000'
 '2021-07-24T21:10:00.000000000' '2021-07-24T21:15:00.000000000'
 '2021-07-24T21:20:00.000000000' '2021-07-24T21:25:00.000000000'
 '2021-07-24T21:30:00.000000000' '2021-07-24T21:35:00.000000000'
 '2021-07-24T21:40:00.000000000' '2021-07-24T21:45:00.000000000'
 '2021-07-24T21:50:00.000000000' '2021-07-24T21:55:00.000000000'
 '2021-07-24T22:00:00.000000000' '2021-07-24T22:05:00.000000000'
 '2021-07-24T22:10:00.000000000' '2021-07-24T22:15:00.000000000'
 '2021-07-24T22:20:00.000000000' '2021-07-24T22:25:00.000000000'
 '2021-07-24T22:30:00.000000000' '2021-07-24T22:35:00.000000000'
 '2021-07-24T22:40:00.000000000' '2021-07-24T22:45:00.000000000'
 '2021-07-24T22:50:00.000000000' '2021-07-24T22:55:00.000000000'
 '2021-07-24T23:00:00.000000000' '2021-07-24T23:05:00.000000000'
 '2021-07-24T23:10:00.000000000' '2021-07-24T23:15:00.000000000'
 '2021-07-24T23:20:00.000000000' '2021-07-24T23:25:00.000000000'
 '2021-07-24T23:30:00.000000000' '2021-07-24T23:35:00.000000000'
 '2021-07-24T23:40:00.000000000' '2021-07-24T23:45:00.000000000'
 '2021-07-24T23:50:00.000000000' '2021-07-24T23:55:00.000000000'
 '2021-07-25T00:00:00.000000000'], obsgeoloc=(0., 0., 0.) m, obsgeovel=(0., 0., 0.) m / s): (ra, dec, distance) in (deg, deg, AU)
    [(123.67199564, 19.83773469, 1.0157858 ),
     (123.67543269, 19.83700363, 1.01578548),
     (123.67886971, 19.83627251, 1.01578517),
     (123.6823067 , 19.83554133, 1.01578485),
     (123.68574365, 19.83481008, 1.01578453),
     (123.68918058, 19.83407876, 1.01578422),
     (123.69261748, 19.83334737, 1.0157839 ),
     (123.69605435, 19.83261592, 1.01578359),
     (123.69949119, 19.83188441, 1.01578327),
     (123.70292801, 19.83115282, 1.01578295),
     (123.70636479, 19.83042117, 1.01578264),
     (123.70980154, 19.82968946, 1.01578232),
     (123.71323826, 19.82895767, 1.015782  ),
     (123.71667496, 19.82822583, 1.01578169),
     (123.72011162, 19.82749391, 1.01578137),
     (123.72354826, 19.82676193, 1.01578106),
     (123.72698486, 19.82602989, 1.01578074),
     (123.73042144, 19.82529777, 1.01578042),
     (123.73385799, 19.82456559, 1.01578011),
     (123.7372945 , 19.82383335, 1.01577979),
     (123.74073099, 19.82310104, 1.01577947),
     (123.74416745, 19.82236866, 1.01577916),
     (123.74760388, 19.82163622, 1.01577884),
     (123.75104028, 19.82090371, 1.01577852),
     (123.75447665, 19.82017113, 1.01577821),
     (123.75791299, 19.81943849, 1.01577789),
     (123.7613493 , 19.81870578, 1.01577757),
     (123.76478559, 19.81797301, 1.01577726),
     (123.76822184, 19.81724017, 1.01577694),
     (123.77165806, 19.81650726, 1.01577662),
     (123.77509426, 19.81577429, 1.01577631),
     (123.77853042, 19.81504125, 1.01577599),
     (123.78196656, 19.81430815, 1.01577567),
     (123.78540266, 19.81357498, 1.01577535),
     (123.78883874, 19.81284174, 1.01577504),
     (123.79227479, 19.81210844, 1.01577472),
     (123.7957108 , 19.81137507, 1.0157744 ),
     (123.79914679, 19.81064163, 1.01577409),
     (123.80258275, 19.80990813, 1.01577377),
     (123.80601868, 19.80917456, 1.01577345),
     (123.80945458, 19.80844093, 1.01577313),
     (123.81289045, 19.80770723, 1.01577282),
     (123.81632629, 19.80697346, 1.0157725 ),
     (123.81976211, 19.80623963, 1.01577218),
     (123.82319789, 19.80550573, 1.01577187),
     (123.82663364, 19.80477177, 1.01577155),
     (123.83006937, 19.80403774, 1.01577123),
     (123.83350506, 19.80330364, 1.01577091),
     (123.83694073, 19.80256948, 1.0157706 ),
     (123.84037636, 19.80183525, 1.01577028),
     (123.84381197, 19.80110096, 1.01576996),
     (123.84724754, 19.8003666 , 1.01576964),
     (123.85068309, 19.79963217, 1.01576932),
     (123.85411861, 19.79889768, 1.01576901),
     (123.8575541 , 19.79816312, 1.01576869),
     (123.86098956, 19.7974285 , 1.01576837),
     (123.86442499, 19.79669381, 1.01576805),
     (123.86786039, 19.79595905, 1.01576774),
     (123.87129576, 19.79522423, 1.01576742),
     (123.8747311 , 19.79448934, 1.0157671 ),
     (123.87816641, 19.79375439, 1.01576678),
     (123.8816017 , 19.79301936, 1.01576646),
     (123.88503695, 19.79228428, 1.01576615),
     (123.88847217, 19.79154913, 1.01576583),
     (123.89190737, 19.79081391, 1.01576551),
     (123.89534253, 19.79007862, 1.01576519),
     (123.89877767, 19.78934327, 1.01576487),
     (123.90221278, 19.78860785, 1.01576455),
     (123.90564785, 19.78787237, 1.01576424),
     (123.9090829 , 19.78713682, 1.01576392),
     (123.91251792, 19.78640121, 1.0157636 ),
     (123.91595291, 19.78566553, 1.01576328),
     (123.91938787, 19.78492978, 1.01576296),
     (123.9228228 , 19.78419397, 1.01576264),
     (123.9262577 , 19.78345809, 1.01576233),
     (123.92969257, 19.78272214, 1.01576201),
     (123.93312741, 19.78198613, 1.01576169),
     (123.93656223, 19.78125006, 1.01576137),
     (123.93999701, 19.78051391, 1.01576105),
     (123.94343176, 19.7797777 , 1.01576073),
     (123.94686649, 19.77904143, 1.01576041),
     (123.95030118, 19.77830509, 1.0157601 ),
     (123.95373585, 19.77756868, 1.01575978),
     (123.95717048, 19.77683221, 1.01575946),
     (123.96060509, 19.77609567, 1.01575914),
     (123.96403967, 19.77535907, 1.01575882),
     (123.96747422, 19.7746224 , 1.0157585 ),
     (123.97090873, 19.77388566, 1.01575818),
     (123.97434322, 19.77314886, 1.01575786),
     (123.97777768, 19.77241199, 1.01575754),
     (123.98121211, 19.77167505, 1.01575723),
     (123.98464652, 19.77093805, 1.01575691),
     (123.98808089, 19.77020099, 1.01575659),
     (123.99151523, 19.76946386, 1.01575627),
     (123.99494954, 19.76872666, 1.01575595),
     (123.99838383, 19.76798939, 1.01575563),
     (124.00181808, 19.76725206, 1.01575531),
     (124.0052523 , 19.76651467, 1.01575499),
     (124.0086865 , 19.76577721, 1.01575467),
     (124.01212066, 19.76503968, 1.01575435),
     (124.0155548 , 19.76430208, 1.01575403),
     (124.01898891, 19.76356442, 1.01575371),
     (124.02242299, 19.7628267 , 1.01575339),
     (124.02585703, 19.76208891, 1.01575307),
     (124.02929105, 19.76135105, 1.01575275),
     (124.03272504, 19.76061313, 1.01575243),
     (124.036159  , 19.75987514, 1.01575211),
     (124.03959293, 19.75913708, 1.01575179),
     (124.04302683, 19.75839896, 1.01575148),
     (124.04646071, 19.75766078, 1.01575116),
     (124.04989455, 19.75692252, 1.01575084),
     (124.05332836, 19.7561842 , 1.01575052),
     (124.05676214, 19.75544582, 1.0157502 ),
     (124.0601959 , 19.75470737, 1.01574988),
     (124.06362962, 19.75396885, 1.01574956),
     (124.06706332, 19.75323027, 1.01574924),
     (124.07049699, 19.75249162, 1.01574892),
     (124.07393062, 19.75175291, 1.0157486 ),
     (124.07736423, 19.75101413, 1.01574828),
     (124.08079781, 19.75027528, 1.01574796),
     (124.08423136, 19.74953637, 1.01574764),
     (124.08766487, 19.7487974 , 1.01574732),
     (124.09109836, 19.74805835, 1.01574699),
     (124.09453182, 19.74731924, 1.01574667),
     (124.09796525, 19.74658007, 1.01574635),
     (124.10139866, 19.74584083, 1.01574603),
     (124.10483203, 19.74510152, 1.01574571),
     (124.10826537, 19.74436215, 1.01574539),
     (124.11169868, 19.74362271, 1.01574507),
     (124.11513197, 19.74288321, 1.01574475),
     (124.11856522, 19.74214364, 1.01574443),
     (124.12199845, 19.741404  , 1.01574411),
     (124.12543164, 19.7406643 , 1.01574379),
     (124.12886481, 19.73992453, 1.01574347),
     (124.13229795, 19.7391847 , 1.01574315),
     (124.13573105, 19.7384448 , 1.01574283),
     (124.13916413, 19.73770484, 1.01574251),
     (124.14259718, 19.73696481, 1.01574219),
     (124.1460302 , 19.73622471, 1.01574187),
     (124.14946319, 19.73548455, 1.01574154),
     (124.15289615, 19.73474432, 1.01574122),
     (124.15632908, 19.73400403, 1.0157409 ),
     (124.15976198, 19.73326367, 1.01574058),
     (124.16319485, 19.73252324, 1.01574026),
     (124.1666277 , 19.73178275, 1.01573994),
     (124.17006051, 19.73104219, 1.01573962),
     (124.17349329, 19.73030157, 1.0157393 ),
     (124.17692605, 19.72956088, 1.01573898),
     (124.18035877, 19.72882013, 1.01573866),
     (124.18379147, 19.72807931, 1.01573833),
     (124.18722413, 19.72733842, 1.01573801),
     (124.19065677, 19.72659747, 1.01573769),
     (124.19408938, 19.72585645, 1.01573737),
     (124.19752196, 19.72511537, 1.01573705),
     (124.20095451, 19.72437422, 1.01573673),
     (124.20438703, 19.72363301, 1.01573641),
     (124.20781952, 19.72289173, 1.01573608),
     (124.21125198, 19.72215038, 1.01573576),
     (124.21468441, 19.72140897, 1.01573544),
     (124.21811681, 19.72066749, 1.01573512),
     (124.22154918, 19.71992595, 1.0157348 ),
     (124.22498152, 19.71918434, 1.01573448),
     (124.22841384, 19.71844266, 1.01573415),
     (124.23184612, 19.71770092, 1.01573383),
     (124.23527838, 19.71695912, 1.01573351),
     (124.2387106 , 19.71621724, 1.01573319),
     (124.2421428 , 19.71547531, 1.01573287),
     (124.24557496, 19.7147333 , 1.01573255),
     (124.2490071 , 19.71399123, 1.01573222)]>

In [64]:
# Mean latitude
mean_lat = (40.76754 + 40.87248)/2.0                 # degrees

# Mean longitude
mean_lon = (-73.96449 - 73.89352)/2.0                # degrees

# Mean altitude
mean_alt = (94.8 + 57.5)/2.0                         # meters

# Set the location
new_york = EarthLocation(lat = mean_lat*u.deg, lon = mean_lon*u.deg, height = mean_alt*u.m)

In [65]:
local_sun = sun.transform_to(AltAz(obstime = t, location = new_york))

In [70]:
np.array(local_sun.az)

array([ 65.0880044 ,  65.89090363,  66.6885197 ,  67.48117328,
        68.26918781,  69.05288957,  69.83260797,  70.60867575,
        71.38142929,  72.15120892,  72.9183593 ,  73.68322984,
        74.44617512,  75.20755543,  75.96773725,  76.72709391,
        77.48600615,  78.24486287,  79.00406185,  79.76401054,
        80.52512692,  81.28784046,  82.05259308,  82.81984024,
        83.59005209,  84.36371471,  85.14133143,  85.92342428,
        86.71053552,  87.50322931,  88.30209348,  89.10774144,
        89.92081428,  90.74198297,  91.57195078,  92.41145583,
        93.26127391,  94.12222145,  94.99515873,  95.88099341,
        96.78068417,  97.6952448 ,  98.62574846,  99.57333228,
       100.5392023 , 101.5246387 , 102.53100143, 103.55973608,
       104.61238015, 105.69056957, 106.79604554, 107.93066151,
       109.09639039, 110.29533167, 111.52971851, 112.80192442,
       114.11446938, 115.47002502, 116.87141839, 118.32163375,
       119.82381179, 121.38124531, 122.99737029, 124.67575121,
       126.4200591 , 128.23404047, 130.12147545, 132.08612282,
       134.13164991, 136.26154528, 138.47901226, 140.78684248,
       143.18726892, 145.68180032, 148.27104021, 150.95449699,
       153.73039449, 156.59549544, 159.5449538 , 162.57221323,
       165.66896994, 168.82521567, 172.02937188, 175.26851869,
       178.52871239, 181.7953751 , 185.0537312 , 188.28925848,
       191.48812035, 194.63754783, 197.72614675, 200.744115  ,
       203.68336509, 206.53755643, 209.30204926, 211.97379642,
       214.55119114, 217.03388814, 219.42261349, 221.71897536,
       223.92528472, 226.04439181, 228.07954183, 230.03425087,
       231.91220197, 233.71716001, 235.45290362, 237.12317197,
       238.7316243 , 240.28181015, 241.77714839, 243.22091326,
       244.61622618, 245.96605186, 247.27319788, 248.54031678,
       249.76991003, 250.96433335, 252.12580292, 253.2564021 ,
       254.35808856, 255.43270141, 256.48196839, 257.50751284,
       258.51086048, 259.49344593, 260.45661892, 261.40165012,
       262.32973676, 263.24200775, 264.13952867, 265.02330624,
       265.89429264, 266.75338946, 267.60145141, 268.43928975,
       269.26767548, 270.08734232, 270.89898947, 271.70328414,
       272.50086397, 273.29233922, 274.07829479, 274.85929217,
       275.63587119, 276.40855164, 277.17783485, 277.94420506,
       278.70813078, 279.47006598, 280.23045129, 280.98971501,
       281.74827411, 282.5065352 , 283.26489531, 284.02374273,
       284.78345777, 285.54441339, 286.30697586, 287.07150534,
       287.83835643, 288.60787865, 289.38041689, 290.15631182,
       290.93590025, 291.71951548, 292.50748756, 293.30014353,
       294.09780768])

In [69]:
np.array(local_sun.alt)

array([ 1.72118445,  2.58138163,  3.44697986,  4.31777717,  5.19357586,
        6.07418221,  6.95940636,  7.84906202,  8.74296633,  9.64093957,
       10.54280497, 11.44838848, 12.35751853, 13.2700258 , 14.18574296,
       15.10450445, 16.0261462 , 16.95050535, 17.87742004, 18.80672907,
       19.73827164, 20.67188702, 21.60741429, 22.54469194, 23.48355758,
       24.42384757, 25.36539662, 26.30803737, 27.25160003, 28.19591186,
       29.14079671, 30.0860745 , 31.03156069, 31.97706562, 32.92239395,
       33.86734392, 34.8117066 , 35.75526512, 36.69779376, 37.639057  ,
       38.57880851, 39.51678998, 40.45272994, 41.38634235, 42.3173252 ,
       43.24535883, 44.17010422, 45.09120102, 46.00826546, 46.920888  ,
       47.82863082, 48.73102501, 49.62756752, 50.51771785, 51.40089438,
       52.27647045, 53.14377005, 54.00206317, 54.85056085, 55.68840976,
       56.51468664, 57.32839228, 58.12844538, 58.91367628, 59.68282067,
       60.43451355, 61.16728368, 61.87954877, 62.569612  , 63.23566025,
       63.87576469, 64.48788457, 65.06987485, 65.61949866, 66.13444532,
       66.61235482, 67.05084906, 67.44757022, 67.80022581, 68.10663944,
       68.3648056 , 68.57294602, 68.72956433, 68.83349577, 68.8839481 ,
       68.88053057, 68.82326857, 68.71260268, 68.54937215, 68.33478427,
       68.07037219, 67.75794449, 67.39953003, 66.99732168, 66.55362191,
       66.07079264, 65.55121101, 64.99723186, 64.41115733, 63.79521325,
       63.15153184, 62.48213985, 61.78895149, 61.07376509, 60.33826277,
       59.58401251, 58.81247179, 58.02499254, 57.22282672, 56.40713245,
       55.57898024, 54.73935932, 53.88918375, 53.02929832, 52.16048419,
       51.28346418, 50.39890772, 49.50743543, 48.60962341, 47.70600709,
       46.79708489, 45.88332149, 44.96515081, 44.04297884, 43.11718607,
       42.18812986, 41.25614648, 40.32155304, 39.38464925, 38.44571898,
       37.50503175, 36.56284402, 35.61940046, 34.67493501, 33.72967195,
       32.78382682, 31.83760731, 30.89121403, 29.94484126, 28.99867764,
       28.0529068 , 27.10770796, 26.16325646, 25.21972429, 24.27728057,
       23.33609197, 22.39632319, 21.45813731, 20.5216962 , 19.58716086,
       18.65469179, 17.72444928, 16.79659374, 15.87128603, 14.94868769,
       14.02896126, 13.11227057, 12.19878094, 11.28865949, 10.38207537,
        9.47919999,  8.58020729,  7.68527396,  6.79457963,  5.90830717,
        5.02664286,  4.14977661,  3.27790219,  2.41121744])

In [72]:
df_m['sun_altitude'] = np.array(local_sun.alt)

In [75]:
df_m

,Date / Time,Air Temp at Surface [degC],Relative Humidity [percent],Avg Wind Speed [m/s],Wind Direction [degrees],Solar Flux [W/m^2],sun_altitude
0,2021-07-24 06:00:00,21.3,66.5,0.9,348,10,1.721184
1,2021-07-24 06:05:00,21.4,66.1,1.1,345,12,2.581382
2,2021-07-24 06:10:00,21.4,66.5,1.3,4,14,3.446980
3,2021-07-24 06:15:00,21.5,65.4,1.3,5,17,4.317777
4,2021-07-24 06:20:00,21.5,65.0,1.5,346,19,5.193576
...,...,...,...,...,...,...,...
164,2021-07-24 19:40:00,25.0,46.8,2.2,168,21,5.908307
165,2021-07-24 19:45:00,24.9,47.3,3.0,167,18,5.026643
166,2021-07-24 19:50:00,24.8,48.0,2.4,184,19,4.149777
167,2021-07-24 19:55:00,24.8,48.0,2.0,182,18,3.277902
168,2021-07-24 20:00:00,24.6,48.1,3.0,169,14,2.411217

In [84]:
df_m = df_m.rename(columns = {df_m.columns[1] : "air_temperature_at_surface_manhattan [degC]",
                                  df_m.columns[2] : "relative_humidity_manhattan [percent]",
                                  df_m.columns[3] : "avg_wind_speed_manhattan [m/s]",
                                  df_m.columns[4] : "wind_direction_manhattan [degrees]",
                                  df_m.columns[5] : "solar_flux_manhattan [W/m^2]"})

In [85]:
df_b = df_b.rename(columns = {df_b.columns[1] : "air_temperature_at_surface_bronx [degC]",
                      df_b.columns[2] : "relative_humidity_bronx [percent]",
                      df_b.columns[3] : "avg_wind_speed_bronx [m/s]",
                      df_b.columns[4] : "wind_direction_bronx [degrees]",
                      df_b.columns[5] : "solar_flux_bronx [W/m^2]"})

In [86]:
pd.concat((df_m, df_b.drop(columns = [df_b.columns[0]])), axis = 1)

,Date / Time,air_temperature_at_surface_manhattan [degC],relative_humidity_manhattan [percent],avg_wind_speed_manhattan [m/s],wind_direction_manhattan [degrees],solar_flux_manhattan [W/m^2],sun_altitude,air_temperature_at_surface_bronx [degC],relative_humidity_bronx [percent],avg_wind_speed_bronx [m/s],wind_direction_bronx [degrees],solar_flux_bronx [W/m^2]
0,2021-07-24 06:00:00,21.3,66.5,0.9,348,10,1.721184,19.3,88.2,0.8,335,12
1,2021-07-24 06:05:00,21.4,66.1,1.1,345,12,2.581382,19.4,87.9,0.8,329,18
2,2021-07-24 06:10:00,21.4,66.5,1.3,4,14,3.446980,19.3,87.6,0.7,321,25
3,2021-07-24 06:15:00,21.5,65.4,1.3,5,17,4.317777,19.4,87.4,0.5,307,33
4,2021-07-24 06:20:00,21.5,65.0,1.5,346,19,5.193576,19.4,87.0,0.2,301,42
...,...,...,...,...,...,...,...,...,...,...,...,...
164,2021-07-24 19:40:00,25.0,46.8,2.2,168,21,5.908307,24.9,49.0,3.5,184,24
165,2021-07-24 19:45:00,24.9,47.3,3.0,167,18,5.026643,24.8,49.0,3.3,173,19
166,2021-07-24 19:50:00,24.8,48.0,2.4,184,19,4.149777,24.9,48.7,3.8,168,17
167,2021-07-24 19:55:00,24.8,48.0,2.0,182,18,3.277902,24.9,47.3,4.1,171,16
168,2021-07-24 20:00:00,24.6,48.1,3.0,169,14,2.411217,24.9,47.4,3.6,162,13

In [80]:
for col in df_m.columns:
    print(col)

Date / Time
Air Temp at Surface [degC]
Relative Humidity [percent]
Avg Wind Speed [m/s]
Wind Direction [degrees]
Solar Flux [W/m^2]
sun_altitude