### EDA of final dataset

In [1]:
# === Packages
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [3]:
# Read dataset
df = pd.read_csv('../data/final_datasets/raw_training_dataset.csv')

In [4]:
df.head()

,ndvi_median_res10,gndvi_median_res10,ndbi_median_res10,ndwi_median_res10,bwdrvi_median_res10,ccci_median_res10,ctvi_median_res10,datt1_median_res10,fe2_median_res10,fo_median_res10,...,polygon_perimeter,polygon_density,air_temperature_at_surface [degC],relative_humidity [percent],avg_wind_speed [m/s],wind_direction [degrees],solar_flux [W/m^2],sun_altitude [deg],sun_azimuth [deg],UHI Index
0,0.206057,0.226649,-0.011038,-0.226649,-0.703608,0.513351,0.840272,0.559904,1.774032,0.978166,...,0.000014,32.0,26.644576,47.49452,3.523739,191.26925,376.849608,48.068118,252.80774,1.030289
1,0.206057,0.226649,-0.011038,-0.226649,-0.703608,0.513351,0.840272,0.559904,1.774032,0.978166,...,0.000014,31.0,26.644576,47.49452,3.523739,191.26925,376.849608,48.068118,252.80774,1.030289
2,0.485089,0.462794,-0.182898,-0.462794,-0.484887,0.679006,0.992517,0.758538,1.565672,0.690763,...,0.000117,32.0,26.644576,47.49452,3.523739,191.26925,376.849608,48.068118,252.80774,1.023798
3,0.495835,0.483479,-0.173959,-0.483479,-0.479290,0.647640,0.997916,0.733288,1.548950,0.703636,...,0.000117,32.0,26.644576,47.49452,3.523739,191.26925,376.849608,48.068118,252.80774,1.023798
4,0.506186,0.478112,-0.143840,-0.478112,-0.506396,0.660960,1.003088,0.745955,1.635692,0.748496,...,0.000117,32.0,26.644576,47.49452,3.523739,191.26925,376.849608,48.068118,252.80774,1.021634

In [5]:
# Check all columns names
for col in df.columns:
    print(col)

ndvi_median_res10
gndvi_median_res10
ndbi_median_res10
ndwi_median_res10
bwdrvi_median_res10
ccci_median_res10
ctvi_median_res10
datt1_median_res10
fe2_median_res10
fo_median_res10
fs_median_res10
msr_median_res10
msavi_median_res10
pvr_median_res10
psndc2_median_res10
siwsi_median_res10
ndmi_median_res10
bndvi_median_res10
nbr_median_res10
pndvi_median_res10
si_median_res10
rbndvi_median_res10
srswirnir_median_res10
sbl_median_res10
w_median_res10
sipi1_median_res10
vari_median_res10
tdvi_median_res10
evi_median_res10
lst_median_res10
polygon_area
polygon_perimeter
polygon_density
air_temperature_at_surface [degC]
relative_humidity [percent]
avg_wind_speed [m/s]
wind_direction [degrees]
solar_flux [W/m^2]
sun_altitude [deg]
sun_azimuth [deg]
UHI Index

In [6]:
# Statistical description of the dataset
df.describe()

,ndvi_median_res10,gndvi_median_res10,ndbi_median_res10,ndwi_median_res10,bwdrvi_median_res10,ccci_median_res10,ctvi_median_res10,datt1_median_res10,fe2_median_res10,fo_median_res10,...,polygon_perimeter,polygon_density,air_temperature_at_surface [degC],relative_humidity [percent],avg_wind_speed [m/s],wind_direction [degrees],solar_flux [W/m^2],sun_altitude [deg],sun_azimuth [deg],UHI Index
count,11229.000000,11229.000000,11229.000000,11229.000000,11229.000000,11227.000000,11229.000000,11227.000000,11229.000000,11229.000000,...,11229.000000,11229.000000,11229.000000,11229.000000,11229.000000,11229.000000,11229.000000,11229.000000,11229.000000,11229.000000
mean,0.206853,0.225783,0.009703,-0.225783,-0.668139,0.316474,0.832869,0.245086,1.896548,1.055824,...,0.000047,21.457298,26.985717,47.237657,3.069336,164.554954,466.530641,51.335468,248.220302,1.000001
std,0.206192,0.175793,0.132000,0.175793,0.163010,12.405375,0.114817,13.542193,0.261832,0.279441,...,0.000038,14.102242,0.414890,2.362124,0.658619,26.313842,183.770833,2.754202,4.012704,0.016238
min,-0.164700,-0.187701,-0.443110,-0.806583,-0.874224,-502.988144,0.579051,-467.000000,1.251409,0.385896,...,0.000002,0.000000,26.197958,40.212151,1.208111,88.185615,118.550392,46.979270,239.046208,0.956122
25%,0.053281,0.095206,-0.063419,-0.309578,-0.766395,0.137621,0.743829,0.157163,1.716692,0.880726,...,0.000020,12.000000,26.716900,46.400000,2.800000,150.119863,292.000000,48.969474,245.161455,0.988577
50%,0.129202,0.165601,0.024390,-0.165601,-0.730732,0.644668,0.793222,0.704268,1.871244,1.050000,...,0.000035,19.000000,26.984223,47.494520,3.180261,162.067070,493.605441,51.107135,248.789160,1.000237
75%,0.295107,0.309578,0.096386,-0.095206,-0.644814,0.896932,0.891687,0.917404,2.040501,1.213333,...,0.000068,28.000000,27.180084,48.135303,3.451944,184.000000,622.617531,53.546350,251.665033,1.011176
max,0.882879,0.806583,0.558525,0.187701,0.179050,367.096112,1.175959,407.000000,4.543398,3.530263,...,0.000237,86.000000,28.304176,51.111528,4.500000,215.185195,786.086163,57.060733,254.139972,1.046036

In [7]:
# Check NaNs
df.isna().sum()

ndvi_median_res10                    0
gndvi_median_res10                   0
ndbi_median_res10                    0
ndwi_median_res10                    0
bwdrvi_median_res10                  0
ccci_median_res10                    2
ctvi_median_res10                    0
datt1_median_res10                   2
fe2_median_res10                     0
fo_median_res10                      0
fs_median_res10                      0
msr_median_res10                     6
msavi_median_res10                   0
pvr_median_res10                     0
psndc2_median_res10                  0
siwsi_median_res10                   0
ndmi_median_res10                    0
bndvi_median_res10                   0
nbr_median_res10                     0
pndvi_median_res10                   0
si_median_res10                      3
rbndvi_median_res10                  0
srswirnir_median_res10               0
sbl_median_res10                     0
w_median_res10                       0
sipi1_median_res10                   2
vari_median_res10                    0
tdvi_median_res10                    0
evi_median_res10                     0
lst_median_res10                     0
polygon_area                         0
polygon_perimeter                    0
polygon_density                      0
air_temperature_at_surface [degC]    0
relative_humidity [percent]          0
avg_wind_speed [m/s]                 0
wind_direction [degrees]             0
solar_flux [W/m^2]                   0
sun_altitude [deg]                   0
sun_azimuth [deg]                    0
UHI Index                            0
dtype: int64

In [8]:
# Check if there are duplicated data in the dataset
df.duplicated().sum()

np.int64(814)

In [9]:
# Print info on each variable
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11229 entries, 0 to 11228
Data columns (total 41 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ndvi_median_res10                  11229 non-null  float64
 1   gndvi_median_res10                 11229 non-null  float64
 2   ndbi_median_res10                  11229 non-null  float64
 3   ndwi_median_res10                  11229 non-null  float64
 4   bwdrvi_median_res10                11229 non-null  float64
 5   ccci_median_res10                  11227 non-null  float64
 6   ctvi_median_res10                  11229 non-null  float64
 7   datt1_median_res10                 11227 non-null  float64
 8   fe2_median_res10                   11229 non-null  float64
 9   fo_median_res10                    11229 non-null  float64
 10  fs_median_res10                    11229 non-null  float64
 11  msr_median_res10                   11223 non-null  float64
 12  msavi_median_res10                 11229 non-null  float64
 13  pvr_median_res10                   11229 non-null  float64
 14  psndc2_median_res10                11229 non-null  float64
 15  siwsi_median_res10                 11229 non-null  float64
 16  ndmi_median_res10                  11229 non-null  float64
 17  bndvi_median_res10                 11229 non-null  float64
 18  nbr_median_res10                   11229 non-null  float64
 19  pndvi_median_res10                 11229 non-null  float64
 20  si_median_res10                    11226 non-null  float64
 21  rbndvi_median_res10                11229 non-null  float64
 22  srswirnir_median_res10             11229 non-null  float64
 23  sbl_median_res10                   11229 non-null  float64
 24  w_median_res10                     11229 non-null  float64
 25  sipi1_median_res10                 11227 non-null  float64
 26  vari_median_res10                  11229 non-null  float64
 27  tdvi_median_res10                  11229 non-null  float64
 28  evi_median_res10                   11229 non-null  float64
 29  lst_median_res10                   11229 non-null  float64
 30  polygon_area                       11229 non-null  float64
 31  polygon_perimeter                  11229 non-null  float64
 32  polygon_density                    11229 non-null  float64
 33  air_temperature_at_surface [degC]  11229 non-null  float64
 34  relative_humidity [percent]        11229 non-null  float64
 35  avg_wind_speed [m/s]               11229 non-null  float64
 36  wind_direction [degrees]           11229 non-null  float64
 37  solar_flux [W/m^2]                 11229 non-null  float64
 38  sun_altitude [deg]                 11229 non-null  float64
 39  sun_azimuth [deg]                  11229 non-null  float64
 40  UHI Index                          11229 non-null  float64
dtypes: float64(41)
memory usage: 3.5 MB

In [17]:
# Check linear correlation between each variable
pearson_cor = df.corr(method = 'pearson').to_numpy()
spearman_cor = df.corr(method = 'spearman').to_numpy()

In [ ]:
# Pipeline to apply to training numerical predictors
numerical_pipeline = Pipeline(steps = [("imputer", SimpleImputer(strategy = "mean")),
                                       ("scaler", StandardScaler())])

In [33]:
preprocessor = ColumnTransformer([("numerical_pipeline", numerical_pipeline, df.columns[:-1])])

In [34]:
input_feature_df = df.drop(columns = ["UHI Index"], axis = 1)

In [35]:
input_feature_arr = preprocessor.fit_transform(input_feature_df)

In [36]:
df_new = pd.DataFrame(np.c_[input_feature_arr, np.array(df[df.columns[-1]])])

In [37]:
df_new.describe()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
count,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,...,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,1.122900e+04,11229.000000
mean,1.113684e-16,1.721147e-16,-2.024879e-17,-1.721147e-16,-1.619903e-16,-3.163874e-19,-3.746026e-16,-1.581937e-18,-1.032688e-15,-4.151002e-16,...,4.049758e-17,-1.012440e-17,4.819212e-15,-2.227367e-16,-8.099516e-17,1.012440e-16,-9.111956e-17,4.252246e-16,6.925087e-15,1.000001
std,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,...,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,1.000045e+00,0.016238
min,-1.802053e+00,-2.352210e+00,-3.430550e+00,-3.304033e+00,-1.264304e+00,-4.057692e+01,-2.210739e+00,-3.450752e+01,-2.464051e+00,-2.397492e+00,...,-1.198151e+00,-1.521620e+00,-1.898800e+00,-2.974365e+00,-2.826076e+00,-2.902379e+00,-1.893640e+00,-1.581726e+00,-2.286364e+00,0.956122
25%,-7.448300e-01,-7.428205e-01,-5.539820e-01,-4.766932e-01,-6.027875e-01,-1.439826e-02,-7.755341e-01,-6.493403e-03,-6.869444e-01,-6.266283e-01,...,-7.332177e-01,-6.706536e-01,-6.479516e-01,-3.546362e-01,-4.089594e-01,-5.485985e-01,-9.497612e-01,-8.590872e-01,-7.623247e-01,0.988577
50%,-3.766110e-01,-3.423621e-01,1.112694e-01,3.423621e-01,-3.839961e-01,2.645064e-02,-3.453195e-01,3.390456e-02,-9.664745e-02,-2.084183e-02,...,-3.172526e-01,-1.742565e-01,-3.603166e-03,1.087471e-01,1.684275e-01,-9.455080e-02,1.473357e-01,-8.290718e-02,1.417707e-01,1.000237
75%,4.280357e-01,4.766932e-01,6.567120e-01,7.428205e-01,1.430970e-01,4.679694e-02,5.123026e-01,4.965156e-02,5.498154e-01,5.636847e-01,...,5.417618e-01,4.639683e-01,4.684987e-01,3.800331e-01,5.809491e-01,7.389993e-01,8.493940e-01,8.027661e-01,8.584947e-01,1.011176
max,3.278766e+00,3.304033e+00,4.157917e+00,2.352210e+00,5.197402e+00,2.957014e+01,2.988283e+00,3.004013e+01,1.010941e+01,8.855359e+00,...,5.050691e+00,4.576972e+00,3.177989e+00,1.640067e+00,2.172314e+00,1.924177e+00,1.738958e+00,2.078831e+00,1.475298e+00,1.046036